# Generated by Django 5.1 on 2024-08-28 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogroApp', '0005_logro_user'),
        ('UsuarioApp', '0001_initial'),
        ('likesApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='likes_clase',
            new_name='Likes',
        ),
        migrations.AlterModelTable(
            name='likes',
            table='likes',
        ),
    ]
