# Generated by Django 5.0.7 on 2024-08-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogroApp', '0002_logro_categoria_logro_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logro',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
