# Generated by Django 5.0.7 on 2024-08-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogroApp', '0004_alter_logro_categoria'),
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UsuarioApp.usuario'),
        ),
    ]
