# Generated by Django 5.0.7 on 2024-08-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(max_length=100)),
                ('fecha', models.DateField()),
                ('imglogro', models.ImageField(null=True, upload_to='logros')),
            ],
        ),
    ]
