# Generated by Django 5.0.7 on 2024-08-09 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogroApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logro',
            name='categoria',
            field=models.CharField(default='Sin categoría', max_length=80),
        ),
        migrations.AddField(
            model_name='logro',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
