# Generated by Django 5.1 on 2024-08-28 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LogroApp', '0005_logro_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logro',
            table='logro',
        ),
    ]
