# Generated by Django 5.0.7 on 2024-08-10 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogroApp', '0005_logro_user'),
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateField()),
                ('Achivement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LogroApp.logro')),
                ('User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UsuarioApp.usuario')),
            ],
        ),
    ]
