# Generated by Django 5.1 on 2024-08-29 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComentarioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='comments',
        ),
    ]
