# Generated by Django 5.1.1 on 2024-09-14 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Académico', 'Academic'), ('Profesional', 'Professional'), ('Deportivo', 'Sport'), ('Cultural y Artístico', 'Cultural_and_Artistic'), ('Social y Comunitario', 'Social_and_Community'), ('Tecnológico', 'Tech'), ('Personal', 'Personal'), ('Emprendimiento', 'Entrepreneurship'), ('Financiero', 'Financial'), ('Medioambiental', 'Environmental'), ('Educación Continua', 'Continuing_Education')], default='Academic', max_length=80)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('achievement_image', models.ImageField(null=True, upload_to='achievementes_img')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
