# Generated by Django 5.1.1 on 2024-09-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AchivementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_image',
            field=models.ImageField(null=True, upload_to='achievements_img'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
