# Generated by Django 5.1.1 on 2024-09-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AchivementApp', '0002_alter_achievement_achievement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
