# Generated by Django 5.1.1 on 2024-09-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AchivementApp', '0004_achievement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_image',
            field=models.ImageField(null=True, upload_to='achievements_img/'),
        ),
    ]
